#!/usr/bin/env bash
#
# gitea.sh — Gitea remote automation for Sentinel cloud sessions.
#
# CONFIDENTIAL — Will Fobbs / Pooled Impact
#
# Each cloud session authenticates to git.pooledimpact.com as its own account:
# the session id is the username and <session-id>@pooledimpact.com is the email.
# This script reads those from the environment and keeps the password out of
# argv, out of remote URLs and out of shell history, so nothing is sent or
# logged in the clear.
#
# Environment consumed (set by the cloud environment):
#   GITEA_URL    https://git.pooledimpact.com
#   GITEA_USER   session id for this environment
#   GITEA_PASS   password (never printed, never placed on a command line)
#   GITEA_Email  <session id>@pooledimpact.com
#
# Usage:
#   ops/scripts/gitea.sh env                  show resolved config (password masked)
#   ops/scripts/gitea.sh save                 write a 0600 env file for this session
#   ops/scripts/gitea.sh whoami               authenticated identity check
#   ops/scripts/gitea.sh repos                repositories this account can see
#   ops/scripts/gitea.sh api <path> [curl..]  raw API call, e.g. api /api/v1/version
#   ops/scripts/gitea.sh clone <owner/repo> [dir]
#   ops/scripts/gitea.sh git-setup            configure git auth for the current repo
#
set -euo pipefail

EMAIL_DOMAIN="pooledimpact.com"
DEFAULT_URL="https://git.pooledimpact.com"

die() { printf 'gitea.sh: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- session id
# The account name is this session's id. Prefer what the environment was given;
# otherwise fall back to the ids the runtime exposes.
session_id() {
  if [ -n "${GITEA_USER:-}" ]; then
    printf '%s' "$GITEA_USER"
  elif [ -n "${CLAUDE_CODE_REMOTE_SESSION_ID:-}" ]; then
    # cse_XXXX and session_XXXX name the same session; normalise to session_.
    printf 'session_%s' "${CLAUDE_CODE_REMOTE_SESSION_ID#cse_}"
  elif [ -n "${CLAUDE_CODE_SESSION_ID:-}" ]; then
    printf 'session_%s' "$CLAUDE_CODE_SESSION_ID"
  else
    die "no session id available; set GITEA_USER"
  fi
}

load_config() {
  GITEA_URL="${GITEA_URL:-$DEFAULT_URL}"
  GITEA_URL="${GITEA_URL%/}"
  case "$GITEA_URL" in
    https://*) ;;
    *) die "refusing a non-HTTPS GITEA_URL: credentials would travel in the clear" ;;
  esac
  G_USER="$(session_id)"
  G_EMAIL="${GITEA_Email:-${G_USER}@${EMAIL_DOMAIN}}"
  G_HOST="${GITEA_URL#https://}"
  G_HOST="${G_HOST%%/*}"
  [ -n "${GITEA_PASS:-}" ] || die "GITEA_PASS is not set"
}

# ------------------------------------------------------------- secret plumbing
# The password is handed to curl through a 0600 config file and to git through
# an askpass helper. It never appears in argv, in a URL, or in the process list.
STATE_DIR="${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}}/sentinel-gitea.$$"
cleanup() { rm -rf "$STATE_DIR"; }
trap cleanup EXIT INT TERM

curl_config() {
  mkdir -p "$STATE_DIR"; chmod 700 "$STATE_DIR"
  local cfg="$STATE_DIR/curlrc"
  ( umask 077; printf 'user = "%s:%s"\n' "$G_USER" "$GITEA_PASS" > "$cfg" )
  printf '%s' "$cfg"
}

api() {
  local path="$1"; shift || true
  case "$path" in /*) ;; *) path="/$path" ;; esac
  curl -sS ${FAIL_FLAG:---fail-with-body} --max-time 30 -K "$(curl_config)" "$@" "${GITEA_URL}${path}"
}

# The askpass helper holds no secret of its own: it reads GITEA_USER/GITEA_PASS
# from the environment of the git process that invokes it. It is persistent so
# that "$(gitea.sh askpass-path)" stays valid after this script exits.
askpass_helper() {
  local dir="${HOME}/.config/sentinel"
  mkdir -p "$dir"; chmod 700 "$dir"
  local helper="$dir/gitea-askpass.sh"
  cat > "$helper" <<'HELPER'
#!/usr/bin/env bash
# Generated by ops/scripts/gitea.sh — contains no credentials.
case "$1" in
  *Username*|*username*) printf '%s\n' "${GITEA_USER:?GITEA_USER not set}" ;;
  *)                     printf '%s\n' "${GITEA_PASS:?GITEA_PASS not set}" ;;
esac
HELPER
  chmod 700 "$helper"
  printf '%s' "$helper"
}

# ------------------------------------------------------------------- commands
cmd_env() {
  load_config
  printf 'GITEA_URL    %s\n' "$GITEA_URL"
  printf 'GITEA_USER   %s\n' "$G_USER"
  printf 'GITEA_Email  %s\n' "$G_EMAIL"
  printf 'GITEA_PASS   set, %s chars (not shown)\n' "${#GITEA_PASS}"
}

# Persist this session's settings so later steps can source them without
# re-deriving anything. The file is 0600 and lives outside the repository.
cmd_save() {
  load_config
  local dir="${HOME}/.config/sentinel"
  mkdir -p "$dir"; chmod 700 "$dir"
  local out="${dir}/gitea-${G_USER}.env"
  ( umask 077
    {
      printf '# Generated by ops/scripts/gitea.sh on %s — do not commit.\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
      printf 'export GITEA_URL=%q\n'   "$GITEA_URL"
      printf 'export GITEA_USER=%q\n'  "$G_USER"
      printf 'export GITEA_Email=%q\n' "$G_EMAIL"
      printf 'export GITEA_PASS=%q\n'  "$GITEA_PASS"
    } > "$out"
  )
  printf 'wrote %s (mode 600)\n' "$out"
  printf 'source it with:  . %s\n' "$out"
}

cmd_whoami() {
  load_config
  api /api/v1/user
  printf '\n'
}

cmd_repos() {
  load_config
  api '/api/v1/user/repos?limit=50' | grep -o '"full_name":"[^"]*"' | cut -d'"' -f4 | grep -v '^$' || true
}

cmd_api() {
  load_config
  [ $# -ge 1 ] || die "usage: gitea.sh api <path> [curl args...]"
  local path="$1"; shift
  api "$path" "$@"
  printf '\n'
}

# Credentials go through the askpass helper, so the remote URL stays clean and
# the password is never written into .git/config.
cmd_clone() {
  load_config
  [ $# -ge 1 ] || die "usage: gitea.sh clone <owner/repo> [dir]"
  local slug="$1"; shift
  GITEA_USER="$G_USER" GIT_ASKPASS="$(askpass_helper)" GIT_TERMINAL_PROMPT=0 \
    git clone "${GITEA_URL}/${slug}.git" "$@"
}

cmd_git_setup() {
  load_config
  git rev-parse --git-dir >/dev/null 2>&1 || die "not inside a git repository"
  git config user.name "$G_USER"
  git config user.email "$G_EMAIL"
  printf 'git identity set to %s <%s>\n' "$G_USER" "$G_EMAIL"
  printf 'for pushes:  GIT_ASKPASS=$(%s askpass-path) git push\n' "$0"
}

cmd_askpass_path() { load_config; askpass_helper; printf '\n'; }

# curl gained --fail-with-body in 7.76; fall back quietly on older builds.
curl --help all 2>/dev/null | grep -q -- '--fail-with-body' || FAIL_FLAG='--fail'


main() {
  local cmd="${1:-env}"; shift || true
  case "$cmd" in
    env)          cmd_env "$@" ;;
    save)         cmd_save "$@" ;;
    whoami)       cmd_whoami "$@" ;;
    repos)        cmd_repos "$@" ;;
    api)          cmd_api "$@" ;;
    clone)        cmd_clone "$@" ;;
    git-setup)    cmd_git_setup "$@" ;;
    askpass-path) cmd_askpass_path "$@" ;;
    -h|--help|help) sed -n '2,30p' "$0" ;;
    *)            die "unknown command: $cmd (try --help)" ;;
  esac
}

main "$@"
